// Extracted photo's info for App.tsx to set states for
export const photoData = [
  {
    id: 1,
    first_name: 'Edward',
    last_name: 'Hay',
    year: 1930,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/Edward_Hay_1930.jpg',
  },
  {
    id: 2,
    first_name: 'Edward',
    last_name: 'Lunn',
    year: 1930,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/Edward_Lunn_1930.jpg',
  },
  {
    id: 3,
    first_name: 'George',
    last_name: 'Harrower',
    year: 1930,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/George_Harrower_1930.jpg',
  },
  {
    id: 4,
    first_name: 'Harold',
    last_name: 'Woodland',
    year: 1930,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/Harold_Woodland_1930.jpg',
  },
  {
    id: 5,
    first_name: 'Ian',
    last_name: 'Adam',
    year: 1930,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/Ian_Adam_1930.jpg',
  },
  {
    id: 6,
    first_name: 'James',
    last_name: 'Mckeever',
    year: 1930,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/James_Mckeever_1930.jpg',
  },
  {
    id: 7,
    first_name: 'James',
    last_name: 'Roberts',
    year: 1930,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/James_Roberts_1930.jpg',
  },
  {
    id: 8,
    first_name: 'John',
    last_name: 'Baker',
    year: 1930,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/John_Baker_1930.jpg',
  },
  {
    id: 9,
    first_name: 'Schubert',
    last_name: 'Fraser',
    year: 1930,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/Schubert_Fraser_1930.jpg',
  },
  {
    id: 10,
    first_name: 'Thomas',
    last_name: 'Hadwin',
    year: 1930,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/Thomas_Hadwin_1930.jpg',
  },
  {
    id: 11,
    first_name: 'C.R.',
    last_name: 'Taylor',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/C.R.Taylor_1937.jpg',
  },
  {
    id: 12,
    first_name: 'C.W.',
    last_name: 'Mcleish',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/C.W.Mcleish_1937.jpg',
  },
  {
    id: 13,
    first_name: 'D.A.',
    last_name: 'Darling',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/D.A.Darling_1937.jpg',
  },
  {
    id: 14,
    first_name: 'D.C.',
    last_name: 'Macphail',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/D.C.Macphail_1937.jpg',
  },
  {
    id: 15,
    first_name: 'D.W.',
    last_name: 'Thomason',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/D.W.Thomason_1937.jpg',
  },
  {
    id: 16,
    first_name: 'F.M.',
    last_name: 'Cazalet',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/F.M.Cazalet_1937.jpg',
  },
  {
    id: 17,
    first_name: 'H.F.',
    last_name: 'Alexander',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/H.F.Alexander_1937.jpg',
  },
  {
    id: 18,
    first_name: 'H.G.',
    last_name: 'Hawkins',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/H.G.Hawkins_1937.jpg',
  },
  {
    id: 19,
    first_name: 'H.R.',
    last_name: 'Gissing',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/H.R.Gissing_1937.jpg',
  },
  {
    id: 20,
    first_name: 'J.A.',
    last_name: 'Polson',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/J.A.Polson_1937.jpg',
  },
  {
    id: 21,
    first_name: 'J.C.',
    last_name: 'Sowerby',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/J.C.Sowerby_1937.jpg',
  },
  {
    id: 22,
    first_name: 'J.L.',
    last_name: 'Witbeck',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/J.L.Witbeck_1937.jpg',
  },
  {
    id: 23,
    first_name: 'J.R.E.',
    last_name: 'Clark',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/J.R.E.Clark_1937.jpg',
  },
  {
    id: 24,
    first_name: 'K.D.',
    last_name: 'Keil',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/K.D.Keil_1937.jpg',
  },
  {
    id: 25,
    first_name: 'M.H.',
    last_name: 'Mackenzie',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/M.H.Mackenzie_1937.jpg',
  },
  {
    id: 26,
    first_name: 'M.L.',
    last_name: 'Calhoun',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/M.L.Calhoun_1937.jpg',
  },
  {
    id: 27,
    first_name: 'M.',
    last_name: 'Long',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/M.Long_1937.jpg',
  },
  {
    id: 28,
    first_name: 'R.D.',
    last_name: 'Hodge',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/R.D.Hodge_1937.jpg',
  },
  {
    id: 29,
    first_name: 'R.S.',
    last_name: 'Obata',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/R.S.Obata_1937.jpg',
  },
  {
    id: 30,
    first_name: 'W.',
    last_name: 'Wolfe',
    year: 1937,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/W.Wolfe_1937.jpg',
  },
  {
    id: 31,
    first_name: 'A.B.',
    last_name: 'Staniforth',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/A.B.Staniforth_1938.jpg',
  },
  {
    id: 32,
    first_name: 'A.',
    last_name: 'Utetzky',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/A.Uretzky_1938.jpg',
  },
  {
    id: 33,
    first_name: 'B.F.',
    last_name: 'Deshaw',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/B.F.Deshaw_1938.jpg',
  },
  {
    id: 34,
    first_name: 'F.T.',
    last_name: 'Kolisnek',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/F.T.Kolisnek_1938.jpg',
  },
  {
    id: 35,
    first_name: 'G.A.',
    last_name: 'Snelling',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/G.A.Snelling_1938.jpg',
  },
  {
    id: 36,
    first_name: 'G.',
    last_name: 'Hargreaves',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/G.Hargreaves_1938.jpg',
  },
  {
    id: 37,
    first_name: 'J.D.',
    last_name: 'Hogg',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/J.D.Hogg_1938.jpg',
  },
  {
    id: 38,
    first_name: 'J.H.',
    last_name: 'Radcliffe',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/J.H.Radcliffe_1938.jpg',
  },
  {
    id: 39,
    first_name: 'J.J.',
    last_name: 'Wighton',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/J.J.Wighton_1938.jpg',
  },
  {
    id: 40,
    first_name: 'L.F.',
    last_name: 'Gary',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/L.F.Gary_1938.jpg',
  },
  {
    id: 41,
    first_name: 'L.',
    last_name: 'Shelling',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/L.Shelling_1938.jpg',
  },
  {
    id: 42,
    first_name: 'N.J.',
    last_name: 'Dunlop',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/N.J.Dunlop_1938.jpg',
  },
  {
    id: 43,
    first_name: 'P.D.',
    last_name: 'Smith',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/P.D.Smith_1938.jpg',
  },
  {
    id: 44,
    first_name: 'R.C.',
    last_name: 'Robinson',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/R.C.Robinson_1938.jpg',
  },
  {
    id: 45,
    first_name: 'R.M.',
    last_name: 'Campbell',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/R.M.Campbell_1938.jpg',
  },
  {
    id: 46,
    first_name: 'R.M.',
    last_name: 'Peebles',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/R.M.Peebles_1938.jpg',
  },
  {
    id: 47,
    first_name: 'W.A.',
    last_name: 'Cloke',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/W.A.Cloke_1938.jpg',
  },
  {
    id: 48,
    first_name: 'W.J.',
    last_name: 'Boyce',
    year: 1938,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1938/W.J.Boyce_1938.jpg',
  },
  {
    id: 49,
    first_name: 'A.',
    last_name: 'Coulson',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/A.Coulson_1939.jpg',
  },
  {
    id: 50,
    first_name: 'A.L.',
    last_name: 'Sutton',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/A.L.Sutton_1939.jpg',
  },
  {
    id: 51,
    first_name: 'A.R.B.',
    last_name: 'McDougal',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/A.R.B.McDougal_1939.jpg',
  },
  {
    id: 52,
    first_name: 'C.E.',
    last_name: 'Hand',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/C.E.Hand_1939.jpg',
  },
  {
    id: 53,
    first_name: 'C.H.',
    last_name: 'Shortley-Lutteral',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/C.H.Shortley-Lutteral_1939.jpg',
  },
  {
    id: 54,
    first_name: 'D.A.',
    last_name: 'Stewart',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/D.A.Stewart_1939.jpg',
  },
  {
    id: 55,
    first_name: 'F.B.',
    last_name: 'Jones',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/F.B.Jones_1939.jpg',
  },
  {
    id: 56,
    first_name: 'G.B.',
    last_name: 'Erlebach',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/G.B.Erlebach_1939.jpg',
  },
  {
    id: 57,
    first_name: 'G.E.',
    last_name: 'Harrison',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/G.E.Harrison_1939.jpg',
  },
  {
    id: 58,
    first_name: 'G.E.',
    last_name: 'McDoweil',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/G.E.McDoweil_1939.jpg',
  },
  {
    id: 59,
    first_name: 'J.E.',
    last_name: 'Breeze',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/J.E.Breeze_1939.jpg',
  },
  {
    id: 60,
    first_name: 'M.P.',
    last_name: 'Larsen',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/M.P.Larsen_1939.jpg',
  },
  {
    id: 61,
    first_name: 'O.R.',
    last_name: 'Fulton',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/O.R.Fulton_1939.jpg',
  },
  {
    id: 62,
    first_name: 'P.J.',
    last_name: 'Farmer',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/P.J.Farmer_1939.jpg',
  },
  {
    id: 63,
    first_name: 'P.R.',
    last_name: 'Layard',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/P.R.Layard_1939.jpg',
  },
  {
    id: 64,
    first_name: 'R.A.',
    last_name: 'Morris',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/R.A.Morris_1939.jpg',
  },
  {
    id: 65,
    first_name: 'R.A.',
    last_name: 'Phillips',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/R.A.Phillips_1939.jpg',
  },
  {
    id: 66,
    first_name: 'R.C.',
    last_name: 'Gordon',
    year: 1939,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1939/R.C.Gordon_1939.jpg',
  },
  {
    id: 67,
    first_name: 'A.',
    last_name: 'Coulson',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/A.Coulson_1940.jpg',
  },
  {
    id: 68,
    first_name: 'A.D.K.',
    last_name: 'Laird',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/A.D.K.Laird_1940.jpg',
  },
  {
    id: 69,
    first_name: 'A.J.',
    last_name: 'Duncan',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/A.J.Duncan_1940.jpg',
  },
  {
    id: 70,
    first_name: 'A.R.M.',
    last_name: 'Stewart',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/A.R.M.Stewart_1940.jpg',
  },
  {
    id: 71,
    first_name: 'D.',
    last_name: 'Cosar',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/D.Cosar_1940.jpg',
  },
  {
    id: 72,
    first_name: 'E.S.',
    last_name: 'Webb',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/E.S.Webb_1940.jpg',
  },
  {
    id: 73,
    first_name: 'G.F.',
    last_name: 'Pearce',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/G.F.Pearce_1940.jpg',
  },
  {
    id: 74,
    first_name: 'G.F.',
    last_name: 'Saito',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/G.F.Saito_1940.jpg',
  },
  {
    id: 75,
    first_name: 'H.',
    last_name: 'Carruthers',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/H.Carruthers_1940.jpg',
  },
  {
    id: 76,
    first_name: 'H.F.',
    last_name: 'Morris',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/H.F.Morris.jpg',
  },
  {
    id: 77,
    first_name: 'J.A.',
    last_name: 'Sanderson',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/J.A.Sanderson_1940.jpg',
  },
  {
    id: 78,
    first_name: 'J.B.',
    last_name: 'Johnsen',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/J.B.Johnsen_1940.jpg',
  },
  {
    id: 79,
    first_name: 'J.K.',
    last_name: 'Gadie',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/J.K.Gadie_1940.jpg',
  },
  {
    id: 80,
    first_name: 'J.R.',
    last_name: 'Pogson',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/J.R.Pogson_1940.jpg',
  },
  {
    id: 81,
    first_name: 'L.A.',
    last_name: 'Monasch',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/L.A.Monasch_1940.jpg',
  },
  {
    id: 82,
    first_name: 'M.M.',
    last_name: 'Kennedy',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/M.M.Kennedy_1940.jpg',
  },
  {
    id: 83,
    first_name: 'R.G.',
    last_name: 'Bogle',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/R.G.Bogle_1940.jpg',
  },
  {
    id: 84,
    first_name: 'S.A.',
    last_name: 'Traresso',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/S.A.Traresso_1940.jpg',
  },
  {
    id: 85,
    first_name: 'W.A.',
    last_name: 'Darker',
    year: 1940,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1940/W.A.Darker_1940.jpg',
  },
  {
    id: 86,
    first_name: 'A.J.',
    last_name: 'Gregory',
    year: 1941,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1941/A.J.Gregory_1941.jpg',
  },
  {
    id: 87,
    first_name: 'A.R.T.',
    last_name: 'Hailey',
    year: 1941,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1941/A.R.T.Hailey_1941.jpg',
  },
  {
    id: 88,
    first_name: 'C.J.',
    last_name: 'Crane',
    year: 1941,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1941/C.J.Crane_1941.jpg',
  },
  {
    id: 89,
    first_name: 'C.V.',
    last_name: 'Ryder',
    year: 1941,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1941/C.V.Ryder_1941.jpg',
  },
  {
    id: 90,
    first_name: 'Cameron B.H.',
    last_name: 'Anderson',
    year: 1941,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1941/Cameron_B.H._Anderson_1941.jpg',
  },
  {
    id: 91,
    first_name: 'Desire P.',
    last_name: 'Morin',
    year: 1941,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1941/Desire_P._Morin_1941.jpg',
  },
  {
    id: 92,
    first_name: 'E. Ler.',
    last_name: 'Lyons',
    year: 1941,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1941/E._Ler._Lyons_1941.jpg',
  },
  {
    id: 93,
    first_name: 'G.K.',
    last_name: 'Davidson',
    year: 1941,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1941/G.K.Davidson_1941.jpg',
  },
  {
    id: 94,
    first_name: 'Garth',
    last_name: 'Griffiths',
    year: 1941,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1941/Garth_Griffiths_1941.jpg',
  },
  {
    id: 95,
    first_name: 'J.D.',
    last_name: 'McDonald',
    year: 1941,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1941/J.D.McDonald_1941.jpg',
  },
  {
    id: 96,
    first_name: 'J.M.',
    last_name: 'Foster',
    year: 1941,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1941/J.M.Foster_1941.jpg',
  },
  {
    id: 97,
    first_name: 'R.',
    last_name: 'Laurence Duke',
    year: 1941,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1941/R._Laurence_Duke_1941.jpg',
  },
  {
    id: 98,
    first_name: 'A.F.',
    last_name: 'Mosher',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/A.F._Mosher_1944.jpg',
  },
  {
    id: 99,
    first_name: 'A.H.',
    last_name: 'Rome',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/A.H._Rome_1944.jpg',
  },
  {
    id: 100,
    first_name: 'B.',
    last_name: 'Bartholomew',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/B._Bartholomew_1944.jpg',
  },
  {
    id: 101,
    first_name: 'C.E.',
    last_name: 'Pearson',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/C.E._Pearson_1944.jpg',
  },
  {
    id: 102,
    first_name: 'E.A.',
    last_name: 'Clarke',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/E.A._Clarke_1944.jpg',
  },
  {
    id: 103,
    first_name: 'F.M.',
    last_name: 'Nosworthy',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/F.M._Nosworthy_1944.jpg',
  },
  {
    id: 104,
    first_name: 'G.F.',
    last_name: 'Auchinleck',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/G.F._Auchinleck_1944.jpg',
  },
  {
    id: 105,
    first_name: 'G.F.',
    last_name: 'Godfrey',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/G.F._Godfrey_1944.jpg',
  },
  {
    id: 106,
    first_name: 'H.',
    last_name: 'Gruenberg',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/H._Gruenberg_1944.jpg',
  },
  {
    id: 107,
    first_name: 'J.B.',
    last_name: 'Gush',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/J.B._Gush_1944.jpg',
  },
  {
    id: 108,
    first_name: 'J.C.',
    last_name: 'Carlyle',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/J.C._Carlyle_1944.jpg',
  },
  {
    id: 110,
    first_name: 'M.F.',
    last_name: 'Wilding',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/M.F._Wilding_1944.jpg',
  },
  {
    id: 111,
    first_name: 'N.J.',
    last_name: 'Filman',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/N.J._Filman_1944.jpg',
  },
  {
    id: 112,
    first_name: 'O.M.',
    last_name: 'Julson',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/O.M._Julson_1944.jpg',
  },
  {
    id: 113,
    first_name: 'R.A.',
    last_name: 'Davidson',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/R.A._Davidson_1944.jpg',
  },
  {
    id: 114,
    first_name: 'R.B.C.',
    last_name: 'Hughes',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/R.B.C._Hughes_1944.jpg',
  },
  {
    id: 115,
    first_name: 'R.C.',
    last_name: 'Hausch',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/R.C._Hausch_1944.jpg',
  },
  {
    id: 116,
    first_name: 'R.J.',
    last_name: 'Legeer',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/R.J._Legeer_1944.jpg',
  },
  {
    id: 117,
    first_name: 'S.J.',
    last_name: 'Beaton',
    year: 1944,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1944/S.J._Beaton_1944.jpg',
  },
  {
    id: 118,
    first_name: 'A.J.',
    last_name: 'Healey',
    year: 1945,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1945/A.J._Healey_1945.jpg',
  },
  {
    id: 119,
    first_name: 'A.J.',
    last_name: 'Roper',
    year: 1945,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1945/A.J._Roper_1945.jpg',
  },
  {
    id: 120,
    first_name: 'D.D.',
    last_name: 'Lytle',
    year: 1945,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1945/D.D._Lytle_1945.jpg',
  },
  {
    id: 121,
    first_name: 'E.A.',
    last_name: 'Creelman',
    year: 1945,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1945/E.A._Creelman_1945.jpg',
  },
  {
    id: 122,
    first_name: 'E.H.',
    last_name: 'Tarrant',
    year: 1945,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1945/E.H._Tarrant_1945.jpg',
  },
  {
    id: 123,
    first_name: 'E.S.',
    last_name: 'Gregory',
    year: 1945,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1945/E.S._Gregory_1945.jpg',
  },
  {
    id: 124,
    first_name: 'G.C.',
    last_name: 'Best',
    year: 1945,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1945/G.C._Best_1945.jpg',
  },
  {
    id: 125,
    first_name: 'H.M.',
    last_name: 'Ellis',
    year: 1945,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1945/H.M._Ellis_1945.jpg',
  },
  {
    id: 126,
    first_name: 'J.F.D.',
    last_name: 'Woodcroft',
    year: 1945,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1945/J.F.D._Woodcroft_1945.jpg',
  },
  {
    id: 127,
    first_name: 'M.',
    last_name: 'Lam',
    year: 1945,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1945/M._Lam_1945.jpg',
  },
  {
    id: 128,
    first_name: 'S.D.',
    last_name: 'Isherwood',
    year: 1945,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1945/S.D._Isherwood_1945.jpg',
  },
  {
    id: 129,
    first_name: 'B.A.',
    last_name: 'Auld',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/B.A._Auld_1946.jpg',
  },
  {
    id: 130,
    first_name: 'E.J.',
    last_name: 'Nalos',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/E.J._Nalos_1946.jpg',
  },
  {
    id: 131,
    first_name: 'G.C.',
    last_name: 'Ascroft',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/G.C._Ascroft_1946.jpg',
  },
  {
    id: 132,
    first_name: 'J.',
    last_name: 'Hammerslag',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/J._Hammerslag_1946.jpg',
  },
  {
    id: 133,
    first_name: 'J.D.',
    last_name: 'Sansum',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/J.D._Sansum_1946.jpg',
  },
  {
    id: 134,
    first_name: 'J.N.',
    last_name: 'Olsen',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/J.N._Olsen_1946.jpg',
  },
  {
    id: 135,
    first_name: 'K.',
    last_name: 'Broe',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/K._Broe_1946.jpg',
  },
  {
    id: 136,
    first_name: 'L.E.',
    last_name: 'Wight',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/L.E._Wight_1946.jpg',
  },
  {
    id: 137,
    first_name: 'Luke',
    last_name: 'Long',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/Luke_Long_1946.jpg',
  },
  {
    id: 138,
    first_name: 'M.W.',
    last_name: 'Bodnar',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/M.W._Bodnar_1946.jpg',
  },
  {
    id: 139,
    first_name: 'N.S.',
    last_name: 'Kent',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/N.S._Kent_1946.jpg',
  },
  {
    id: 140,
    first_name: 'Peter',
    last_name: 'Lindenfeld',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/Peter_Lindenfeld_1946.jpg',
  },
  {
    id: 141,
    first_name: 'R.',
    last_name: 'Fisher',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/R._Fisher_1946.jpg',
  },
  {
    id: 142,
    first_name: 'S.B.',
    last_name: 'Howlett',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/S.B._Howlett_1946.jpg',
  },
  {
    id: 143,
    first_name: 'W.E.',
    last_name: 'Kenny',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/W.E._Kenny_1946.jpg',
  },
  {
    id: 144,
    first_name: 'W.G.',
    last_name: 'McMichael',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/W.G._McMichael_1946.jpg',
  },
  {
    id: 145,
    first_name: 'W.J.M.',
    last_name: 'Moore',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/W.J.M._Moore_1946.jpg',
  },
  {
    id: 146,
    first_name: 'W.R.',
    last_name: 'Cheriton',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/W.R._Cheriton_1946.jpg',
  },
  {
    id: 147,
    first_name: 'W.V.',
    last_name: 'Nicholson',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/W.V._Nicholson_1946.jpg',
  },
  {
    id: 148,
    first_name: 'Walter',
    last_name: 'Marks',
    year: 1946,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1946/Walter_Marks_1946.jpg',
  },
  {
    id: 149,
    first_name: 'A.L.',
    last_name: 'McCarthy',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/A.L._McCarthy_1947.jpg',
  },
  {
    id: 150,
    first_name: 'D.J.',
    last_name: 'Evans',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/D.J._Evans_1947.jpg',
  },
  {
    id: 151,
    first_name: 'David A.',
    last_name: 'Hazlewood',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/David_A._Hazlewood_1947.jpg',
  },
  {
    id: 152,
    first_name: 'E.',
    last_name: 'Marzocco',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/E._Marzocco_1947.jpg',
  },
  {
    id: 153,
    first_name: 'E.E.',
    last_name: 'Cooper',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/E.E._Cooper_1947.jpg',
  },
  {
    id: 154,
    first_name: 'E.S.',
    last_name: 'Morisson',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/E.S._Morisson_1947.jpg',
  },
  {
    id: 155,
    first_name: 'Eric J.',
    last_name: 'Woods',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/Eric_J._Woods_1947.jpg',
  },
  {
    id: 156,
    first_name: 'Erling',
    last_name: 'Hesla',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/Erling_Hesla_1947.jpg',
  },
  {
    id: 157,
    first_name: 'Evan',
    last_name: 'Beal',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/Evan_Beal_1947.jpg',
  },
  {
    id: 158,
    first_name: 'G.G.',
    last_name: 'Kirkpatrick',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/G.G._Kirkpatrick_1947.jpg',
  },
  {
    id: 159,
    first_name: 'George',
    last_name: 'Gamble',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/George_Gamble_1947.jpg',
  },
  {
    id: 160,
    first_name: 'George',
    last_name: 'Ward',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/George_Ward_1947.jpg',
  },
  {
    id: 161,
    first_name: 'Gordon',
    last_name: 'Carter',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/Gordon_Carter_1947.jpg',
  },
  {
    id: 162,
    first_name: 'Gordon',
    last_name: 'Genge',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/Gordon_Genge_1947.jpg',
  },
  {
    id: 163,
    first_name: 'Gordon',
    last_name: 'Ralston',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/Gordon_Ralston_1947.jpg',
  },
  {
    id: 164,
    first_name: 'Gus',
    last_name: 'Sainas',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/Gus_Sainas_1947.jpg',
  },
  {
    id: 165,
    first_name: 'Jack',
    last_name: 'Hannan',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/Jack_Hannan_1947.jpg',
  },
  {
    id: 166,
    first_name: 'John',
    last_name: 'Hayes',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/John_Hayes_1947.jpg',
  },
  {
    id: 167,
    first_name: 'K.H.W.',
    last_name: 'Seppala',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/K.H.W._Seppala_1947.jpg',
  },
  {
    id: 168,
    first_name: 'L.B.',
    last_name: 'Davies',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/L.B._Davies_1947.jpg',
  },
  {
    id: 169,
    first_name: 'M.',
    last_name: 'Pavich',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/M._Pavich_1947.jpg',
  },
  {
    id: 170,
    first_name: 'M.',
    last_name: 'Lewchuk',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/M._Lewchuk_1947.jpg',
  },
  {
    id: 171,
    first_name: 'N.H.',
    last_name: 'Glover',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/N.H._Glover_1947.jpg',
  },
  {
    id: 172,
    first_name: 'R.A.',
    last_name: 'Cox',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/R.A._Cox_1947.jpg',
  },
  {
    id: 173,
    first_name: 'R.E.',
    last_name: 'Cook',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/R.E._Cook_1947.jpg',
  },
  {
    id: 174,
    first_name: 'R.M.',
    last_name: 'MacDonald',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/R.M._MacDonald_1947.jpg',
  },
  {
    id: 175,
    first_name: 'R.W.',
    last_name: 'Lister',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/R.W._Lister_1947.jpg',
  },
  {
    id: 176,
    first_name: 'R.W.',
    last_name: 'Racine',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/R.W._Racine_1947.jpg',
  },
  {
    id: 177,
    first_name: 'Rod',
    last_name: 'James',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/Rod._James_1947.jpg',
  },
  {
    id: 178,
    first_name: 'Roy',
    last_name: 'Bushfield',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/Roy_Bushfield_1947.jpg',
  },
  {
    id: 179,
    first_name: 'Stanley G.',
    last_name: 'Thomson',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/Stanley_G._Thomson_1947.jpg',
  },
  {
    id: 180,
    first_name: 'Tom',
    last_name: 'Naylor',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/Tom_Naylor_1947.jpg',
  },
  {
    id: 181,
    first_name: 'W.',
    last_name: 'Hrynchuk',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/W._Hrynchuk_1947.jpg',
  },
  {
    id: 182,
    first_name: 'W.D.',
    last_name: 'Gill',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/W.D._Gill_1947.jpg',
  },
  {
    id: 183,
    first_name: 'Wally',
    last_name: 'Miller',
    year: 1947,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1947/Wally_Miller_1947.jpg',
  },
  {
    id: 184,
    first_name: 'A.',
    last_name: 'Bradfield',
    year: 1942,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1942/A._Bradfield_1942.jpg',
  },
  {
    id: 185,
    first_name: 'D.H.',
    last_name: 'Bastin',
    year: 1942,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1942/D.H._Bastin_1942.jpg',
  },
  {
    id: 186,
    first_name: 'E.N.',
    last_name: 'Walton',
    year: 1942,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1942/E.N._Walton_1942.jpg',
  },
  {
    id: 187,
    first_name: 'F.',
    last_name: 'Jamieson',
    year: 1942,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1942/F._Jamieson_1942.jpg',
  },
  {
    id: 188,
    first_name: 'H.S.',
    last_name: 'Davie',
    year: 1942,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1942/H.S._Davie_1942.jpg',
  },
  {
    id: 189,
    first_name: 'H.V.',
    last_name: 'Casson',
    year: 1942,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1942/H.V._Casson_1942.jpg',
  },
  {
    id: 190,
    first_name: 'J.A.',
    last_name: 'Collins',
    year: 1942,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1942/J.A._Collins_1942.jpg',
  },
  {
    id: 191,
    first_name: 'J.D.',
    last_name: 'Chu',
    year: 1942,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1942/J.D._Chu_1942.jpg',
  },
  {
    id: 192,
    first_name: 'J.F.',
    last_name: 'Hills',
    year: 1942,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1942/J.F._Hills_1942.jpg',
  },
  {
    id: 193,
    first_name: 'L.',
    last_name: 'Zitko',
    year: 1942,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1942/L._Zitko_1942.jpg',
  },
  {
    id: 194,
    first_name: 'L.P.',
    last_name: 'Bundy',
    year: 1942,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1942/L.P._Bundy_1942.jpg',
  },
  {
    id: 195,
    first_name: 'R.',
    last_name: 'Rich',
    year: 1942,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1942/R._Rich_1942.jpg',
  },
  // Entries for 1943
  {
    id: 196,
    first_name: 'A.H.',
    last_name: 'Elliot',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/A.H._Elliot_1943.jpg',
  },
  {
    id: 197,
    first_name: 'A.J.',
    last_name: 'Stewart',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/A.J._Stewart_1943.jpg',
  },
  {
    id: 198,
    first_name: 'D.G.',
    last_name: 'Jessup',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/D.G._Jessup_1943.jpg',
  },
  {
    id: 199,
    first_name: 'D.T.S.',
    last_name: 'Leong',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/D.T.S._Leong_1943.jpg',
  },
  {
    id: 200,
    first_name: 'E.A.',
    last_name: 'Bourne',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/E.A._Bourne_1943.jpg',
  },
  {
    id: 201,
    first_name: 'F.J.',
    last_name: 'Gordon',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/F.J._Gordon_1943.jpg',
  },
  {
    id: 202,
    first_name: 'J.B.R.',
    last_name: 'Fraser',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/J.B.R._Fraser_1943.jpg',
  },
  {
    id: 203,
    first_name: 'J.H.',
    last_name: 'Baldwin',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/J.H._Baldwin_1943.jpg',
  },
  {
    id: 204,
    first_name: 'J.S.',
    last_name: 'Gray',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/J.S._Gray_1943.jpg',
  },
  {
    id: 205,
    first_name: 'L.A.',
    last_name: 'Patterson',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/L.A._Patterson_1943.jpg',
  },
  {
    id: 206,
    first_name: 'L.R.',
    last_name: 'McLellan',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/L.R._McLellan_1943.jpg',
  },
  {
    id: 207,
    first_name: 'O.J.',
    last_name: 'Hayles',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/O.J._Hayles_1943.jpg',
  },
  {
    id: 208,
    first_name: 'R.B.',
    last_name: 'Carter',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/R.B._Carter_1943.jpg',
  },
  {
    id: 209,
    first_name: 'R.C.',
    last_name: 'Miller',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/R.C._Miller_1943.jpg',
  },
  {
    id: 210,
    first_name: 'R.V.L.',
    last_name: 'Handforth',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/R.V.L._Handforth_1943.jpg',
  },
  {
    id: 211,
    first_name: 'S.C.',
    last_name: 'Roberts',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/S.C._Roberts_1943.jpg',
  },
  {
    id: 212,
    first_name: 'S.G.',
    last_name: 'Patterson',
    year: 1943,
    path: 'https://people.ece.ubc.ca/~haileynadine/assets/1943/S.G._Patterson_1943.jpg',
  },
];
