// Extracted photo's info for App.tsx to set states for
export const photoData = [
  {
    id: 1,
    first_name: 'Edward',
    last_name: 'Hay',
    year: 1930,
    path: 'assets/Edward_Hay_1930.jpg',
  },
  {
    id: 2,
    first_name: 'Edward',
    last_name: 'Lunn',
    year: 1930,
    path: 'assets/Edward_Lunn_1930.jpg',
  },
  {
    id: 3,
    first_name: 'George',
    last_name: 'Harrower',
    year: 1930,
    path: 'assets/George_Harrower_1930.jpg',
  },
  {
    id: 4,
    first_name: 'Harold',
    last_name: 'Woodland',
    year: 1930,
    path: 'assets/Harold_Woodland_1930.jpg',
  },
  {
    id: 5,
    first_name: 'Ian',
    last_name: 'Adam',
    year: 1930,
    path: 'assets/Ian_Adam_1930.jpg',
  },
  {
    id: 6,
    first_name: 'James',
    last_name: 'Mckeever',
    year: 1930,
    path: 'assets/James_Mckeever_1930.jpg',
  },
  {
    id: 7,
    first_name: 'James',
    last_name: 'Roberts',
    year: 1930,
    path: 'assets/James_Roberts_1930.jpg',
  },
  {
    id: 8,
    first_name: 'John',
    last_name: 'Baker',
    year: 1930,
    path: 'assets/John_Baker_1930.jpg',
  },
  {
    id: 9,
    first_name: 'Schubert',
    last_name: 'Fraser',
    year: 1930,
    path: 'assets/Schubert_Fraser_1930.jpg',
  },
  {
    id: 10,
    first_name: 'Thomas',
    last_name: 'Hadwin',
    year: 1930,
    path: 'assets/Thomas_Hadwin_1930.jpg',
  },
  {
    id: 11,
    first_name: 'C.R.',
    last_name: 'Taylor',
    year: 1937,
    path: 'assets/C.R.Taylor_1937.jpg',
  },
  {
    id: 12,
    first_name: 'C.W.',
    last_name: 'Mcleish',
    year: 1937,
    path: 'assets/C.W.Mcleish_1937.jpg',
  },
  {
    id: 13,
    first_name: 'D.A.',
    last_name: 'Darling',
    year: 1937,
    path: 'assets/D.A.Darling_1937.jpg',
  },
  {
    id: 14,
    first_name: 'D.C.',
    last_name: 'Macphail',
    year: 1937,
    path: 'assets/D.C.Macphail_1937.jpg',
  },
  {
    id: 15,
    first_name: 'D.W.',
    last_name: 'Thomason',
    year: 1937,
    path: 'assets/D.W.Thomason_1937.jpg',
  },
  {
    id: 16,
    first_name: 'F.M.',
    last_name: 'Cazalet',
    year: 1937,
    path: 'assets/F.M.Cazalet_1937.jpg',
  },
  {
    id: 17,
    first_name: 'H.F.',
    last_name: 'Alexander',
    year: 1937,
    path: 'assets/H.F.Alexander_1937.jpg',
  },
  {
    id: 18,
    first_name: 'H.G.',
    last_name: 'Hawkins',
    year: 1937,
    path: 'assets/H.G.Hawkins_1937.jpg',
  },
  {
    id: 19,
    first_name: 'H.R.',
    last_name: 'Gissing',
    year: 1937,
    path: 'assets/H.R.Gissing_1937.jpg',
  },
  {
    id: 20,
    first_name: 'J.A.',
    last_name: 'Polson',
    year: 1937,
    path: 'assets/J.A.Polson_1937.jpg',
  },
  {
    id: 21,
    first_name: 'J.C.',
    last_name: 'Sowerby',
    year: 1937,
    path: 'assets/J.C.Sowerby_1937.jpg',
  },
  {
    id: 22,
    first_name: 'J.L.',
    last_name: 'Witbeck',
    year: 1937,
    path: 'assets/J.L.Witbeck_1937.jpg',
  },
  {
    id: 23,
    first_name: 'J.R.E.',
    last_name: 'Clark',
    year: 1937,
    path: 'assets/J.R.E.Clark_1937.jpg',
  },
  {
    id: 24,
    first_name: 'K.D.',
    last_name: 'Keil',
    year: 1937,
    path: 'assets/K.D.Keil_1937.jpg',
  },
  {
    id: 25,
    first_name: 'M.H.',
    last_name: 'Mackenzie',
    year: 1937,
    path: 'assets/M.H.Mackenzie_1937.jpg',
  },
  {
    id: 26,
    first_name: 'M.L.',
    last_name: 'Calhoun',
    year: 1937,
    path: 'assets/M.L.Calhoun_1937.jpg',
  },
  {
    id: 27,
    first_name: 'M.',
    last_name: 'Long',
    year: 1937,
    path: 'assets/M.Long_1937.jpg',
  },
  {
    id: 28,
    first_name: 'R.D.',
    last_name: 'Hodge',
    year: 1937,
    path: 'assets/R.D.Hodge_1937.jpg',
  },
  {
    id: 29,
    first_name: 'R.S.',
    last_name: 'Obata',
    year: 1937,
    path: 'assets/R.S.Obata_1937.jpg',
  },
  {
    id: 30,
    first_name: 'W.',
    last_name: 'Wolfe',
    year: 1937,
    path: 'assets/W.Wolfe_1937.jpg',
  },
  {
    id: 31,
    first_name: 'A.B.',
    last_name: 'Staniforth',
    year: 1938,
    path: 'assets/1938/A.B.Staniforth_1938.jpg',
  },
  {
    id: 32,
    first_name: 'A.',
    last_name: 'Utetzky',
    year: 1938,
    path: 'assets/1938/A.Uretzky_1938.jpg',
  },
  {
    id: 33,
    first_name: 'B.F.',
    last_name: 'Deshaw',
    year: 1938,
    path: 'assets/1938/B.F.Deshaw_1938.jpg',
  },
  {
    id: 34,
    first_name: 'F.T.',
    last_name: 'Kolisnek',
    year: 1938,
    path: 'assets/1938/F.T.Kolisnek_1938.jpg',
  },
  {
    id: 35,
    first_name: 'G.A.',
    last_name: 'Snelling',
    year: 1938,
    path: 'assets/1938/G.A.Snelling_1938.jpg',
  },
  {
    id: 36,
    first_name: 'G.',
    last_name: 'Hargreaves',
    year: 1938,
    path: 'assets/1938/G.Hargreaves_1938.jpg',
  },
  {
    id: 37,
    first_name: 'J.D.',
    last_name: 'Hogg',
    year: 1938,
    path: 'assets/1938/J.D.Hogg_1938.jpg',
  },
  {
    id: 38,
    first_name: 'J.H.',
    last_name: 'Radcliffe',
    year: 1938,
    path: 'assets/1938/J.H.Radcliffe_1938.jpg',
  },
  {
    id: 39,
    first_name: 'J.J.',
    last_name: 'Wighton',
    year: 1938,
    path: 'assets/1938/J.J.Wighton_1938.jpg',
  },
  {
    id: 40,
    first_name: 'L.F.',
    last_name: 'Gary',
    year: 1938,
    path: 'assets/1938/L.F.Gary_1938.jpg',
  },
  {
    id: 41,
    first_name: 'L.',
    last_name: 'Shelling',
    year: 1938,
    path: 'assets/1938/L.Shelling_1938.jpg',
  },
  {
    id: 42,
    first_name: 'N.J.',
    last_name: 'Dunlop',
    year: 1938,
    path: 'assets/1938/N.J.Dunlop_1938.jpg',
  },
  {
    id: 43,
    first_name: 'P.D.',
    last_name: 'Smith',
    year: 1938,
    path: 'assets/1938/P.D.Smith_1938.jpg',
  },
  {
    id: 44,
    first_name: 'R.C.',
    last_name: 'Robinson',
    year: 1938,
    path: 'assets/1938/R.C.Robinson_1938.jpg',
  },
  {
    id: 45,
    first_name: 'R.M.',
    last_name: 'Campbell',
    year: 1938,
    path: 'assets/1938/R.M.Campbell_1938.jpg',
  },
  {
    id: 46,
    first_name: 'R.M.',
    last_name: 'Peebles',
    year: 1938,
    path: 'assets/1938/R.M.Peebles_1938.jpg',
  },
  {
    id: 47,
    first_name: 'W.A.',
    last_name: 'Cloke',
    year: 1938,
    path: 'assets/1938/W.A.Cloke_1938.jpg',
  },
  {
    id: 48,
    first_name: 'W.J.',
    last_name: 'Boyce',
    year: 1938,
    path: 'assets/1938/W.J.Boyce_1938.jpg',
  },
  {
    id: 49,
    first_name: 'A.',
    last_name: 'Coulson',
    year: 1939,
    path: 'assets/1939/A.Coulson_1939.jpg',
  },
  {
    id: 50,
    first_name: 'A.L.',
    last_name: 'Sutton',
    year: 1939,
    path: 'assets/1939/A.L.Sutton_1939.jpg',
  },
  {
    id: 51,
    first_name: 'A.R.B.',
    last_name: 'McDougal',
    year: 1939,
    path: 'assets/1939/A.R.B.McDougal_1939.jpg',
  },
  {
    id: 52,
    first_name: 'C.E.',
    last_name: 'Hand',
    year: 1939,
    path: 'assets/1939/C.E.Hand_1939.jpg',
  },
  {
    id: 53,
    first_name: 'C.H.',
    last_name: 'Shortley-Lutteral',
    year: 1939,
    path: 'assets/1939/C.H.Shortley-Lutteral_1939.jpg',
  },
  {
    id: 54,
    first_name: 'D.A.',
    last_name: 'Stewart',
    year: 1939,
    path: 'assets/1939/D.A.Stewart_1939.jpg',
  },
  {
    id: 55,
    first_name: 'F.B.',
    last_name: 'Jones',
    year: 1939,
    path: 'assets/1939/F.B.Jones_1939.jpg',
  },
  {
    id: 56,
    first_name: 'G.B.',
    last_name: 'Erlebach',
    year: 1939,
    path: 'assets/1939/G.B.Erlebach_1939.jpg',
  },
  {
    id: 57,
    first_name: 'G.E.',
    last_name: 'Harrison',
    year: 1939,
    path: 'assets/1939/G.E.Harrison_1939.jpg',
  },
  {
    id: 58,
    first_name: 'G.E.',
    last_name: 'McDoweil',
    year: 1939,
    path: 'assets/1939/G.E.McDoweil_1939.jpg',
  },
  {
    id: 59,
    first_name: 'J.E.',
    last_name: 'Breeze',
    year: 1939,
    path: 'assets/1939/J.E.Breeze_1939.jpg',
  },
  {
    id: 60,
    first_name: 'M.P.',
    last_name: 'Larsen',
    year: 1939,
    path: 'assets/1939/M.P.Larsen_1939.jpg',
  },
  {
    id: 61,
    first_name: 'O.R.',
    last_name: 'Fulton',
    year: 1939,
    path: 'assets/1939/O.R.Fulton_1939.jpg',
  },
  {
    id: 62,
    first_name: 'P.J.',
    last_name: 'Farmer',
    year: 1939,
    path: 'assets/1939/P.J.Farmer_1939.jpg',
  },
  {
    id: 63,
    first_name: 'P.R.',
    last_name: 'Layard',
    year: 1939,
    path: 'assets/1939/P.R.Layard_1939.jpg',
  },
  {
    id: 64,
    first_name: 'R.A.',
    last_name: 'Morris',
    year: 1939,
    path: 'assets/1939/R.A.Morris_1939.jpg',
  },
  {
    id: 65,
    first_name: 'R.A.',
    last_name: 'Phillips',
    year: 1939,
    path: 'assets/1939/R.A.Phillips_1939.jpg',
  },
  {
    id: 66,
    first_name: 'R.C.',
    last_name: 'Gordon',
    year: 1939,
    path: 'assets/1939/R.C.Gordon_1939.jpg',
  },
  {
    id: 67,
    first_name: 'A.',
    last_name: 'Coulson',
    year: 1940,
    path: 'assets/1940/A.Coulson_1940.jpg',
  },
  {
    id: 68,
    first_name: 'A.D.K.',
    last_name: 'Laird',
    year: 1940,
    path: 'assets/1940/A.D.K.Laird_1940.jpg',
  },
  {
    id: 69,
    first_name: 'A.J.',
    last_name: 'Duncan',
    year: 1940,
    path: 'assets/1940/A.J.Duncan_1940.jpg',
  },
  {
    id: 70,
    first_name: 'A.R.M.',
    last_name: 'Stewart',
    year: 1940,
    path: 'assets/1940/A.R.M.Stewart_1940.jpg',
  },
  {
    id: 71,
    first_name: 'D.',
    last_name: 'Cosar',
    year: 1940,
    path: 'assets/1940/D.Cosar_1940.jpg',
  },
  {
    id: 72,
    first_name: 'E.S.',
    last_name: 'Webb',
    year: 1940,
    path: 'assets/1940/E.S.Webb_1940.jpg',
  },
  {
    id: 73,
    first_name: 'G.F.',
    last_name: 'Pearce',
    year: 1940,
    path: 'assets/1940/G.F.Pearce_1940.jpg',
  },
  {
    id: 74,
    first_name: 'G.F.',
    last_name: 'Saito',
    year: 1940,
    path: 'assets/1940/G.F.Saito_1940.jpg',
  },
  {
    id: 75,
    first_name: 'H.',
    last_name: 'Carruthers',
    year: 1940,
    path: 'assets/1940/H.Carruthers_1940.jpg',
  },
  {
    id: 76,
    first_name: 'H.F.',
    last_name: 'Morris',
    year: 1940,
    path: 'assets/1940/H.F.Morris.jpg',
  },
  {
    id: 77,
    first_name: 'J.A.',
    last_name: 'Sanderson',
    year: 1940,
    path: 'assets/1940/J.A.Sanderson_1940.jpg',
  },
  {
    id: 78,
    first_name: 'J.B.',
    last_name: 'Johnsen',
    year: 1940,
    path: 'assets/1940/J.B.Johnsen_1940.jpg',
  },
  {
    id: 79,
    first_name: 'J.K.',
    last_name: 'Gadie',
    year: 1940,
    path: 'assets/1940/J.K.Gadie_1940.jpg',
  },
  {
    id: 80,
    first_name: 'J.R.',
    last_name: 'Pogson',
    year: 1940,
    path: 'assets/1940/J.R.Pogson_1940.jpg',
  },
  {
    id: 81,
    first_name: 'L.A.',
    last_name: 'Monasch',
    year: 1940,
    path: 'assets/1940/L.A.Monasch_1940.jpg',
  },
  {
    id: 82,
    first_name: 'M.M.',
    last_name: 'Kennedy',
    year: 1940,
    path: 'assets/1940/M.M.Kennedy_1940.jpg',
  },
  {
    id: 83,
    first_name: 'R.G.',
    last_name: 'Bogle',
    year: 1940,
    path: 'assets/1940/R.G.Bogle_1940.jpg',
  },
  {
    id: 84,
    first_name: 'S.A.',
    last_name: 'Traresso',
    year: 1940,
    path: 'assets/1940/S.A.Traresso_1940.jpg',
  },
  {
    id: 85,
    first_name: 'W.A.',
    last_name: 'Darker',
    year: 1940,
    path: 'assets/1940/W.A.Darker_1940.jpg',
  },
  {
    id: 86,
    first_name: 'A.J.',
    last_name: 'Gregory',
    year: 1941,
    path: 'assets/1941/A.J.Gregory_1941.jpg',
  },
  {
    id: 87,
    first_name: 'A.R.T.',
    last_name: 'Hailey',
    year: 1941,
    path: 'assets/1941/A.R.T.Hailey_1941.jpg',
  },
  {
    id: 88,
    first_name: 'C.J.',
    last_name: 'Crane',
    year: 1941,
    path: 'assets/1941/C.J.Crane_1941.jpg',
  },
  {
    id: 89,
    first_name: 'C.V.',
    last_name: 'Ryder',
    year: 1941,
    path: 'assets/1941/C.V.Ryder_1941.jpg',
  },
  {
    id: 90,
    first_name: 'Cameron B.H.',
    last_name: 'Anderson',
    year: 1941,
    path: 'assets/1941/Cameron_B.H._Anderson_1941.jpg',
  },
  {
    id: 91,
    first_name: 'Desire P.',
    last_name: 'Morin',
    year: 1941,
    path: 'assets/1941/Desire_P._Morin_1941.jpg',
  },
  {
    id: 92,
    first_name: 'E. Ler.',
    last_name: 'Lyons',
    year: 1941,
    path: 'assets/1941/E._Ler._Lyons_1941.jpg',
  },
  {
    id: 93,
    first_name: 'G.K.',
    last_name: 'Davidson',
    year: 1941,
    path: 'assets/1941/G.K.Davidson_1941.jpg',
  },
  {
    id: 94,
    first_name: 'Garth',
    last_name: 'Griffiths',
    year: 1941,
    path: 'assets/1941/Garth_Griffiths_1941.jpg',
  },
  {
    id: 95,
    first_name: 'J.D.',
    last_name: 'McDonald',
    year: 1941,
    path: 'assets/1941/J.D.McDonald_1941.jpg',
  },
  {
    id: 96,
    first_name: 'J.M.',
    last_name: 'Foster',
    year: 1941,
    path: 'assets/1941/J.M.Foster_1941.jpg',
  },
  {
    id: 97,
    first_name: 'R.',
    last_name: 'Laurence Duke',
    year: 1941,
    path: 'assets/1941/R._Laurence_Duke_1941.jpg',
  },
];
